#!/bin/bash

case "$1" in
    configure)
        if [ -d /var/log/$DPKG_MAINTSCRIPT_PACKAGE/ ]; then
            echo "log directory already exists"
        else
            mkdir -m 0777 -p /var/log/$DPKG_MAINTSCRIPT_PACKAGE
        fi

        cd /var/lib/$DPKG_MAINTSCRIPT_PACKAGE

        if [ -e /var/lib/$DPKG_MAINTSCRIPT_PACKAGE/sentry.conf.py ]; then
		echo "Do you wish to run upgrade procedures (assuming sentry.conf.py has correct settings)?"
		select yn in "Yes" "No"; do
			case $yn in
				Yes ) source bin/activate; cd /var/lib/$DPKG_MAINTSCRIPT_PACKAGE/bin; sentry --config=../sentry.conf.py upgrade; deactivate; break;;
				No ) exit;;
			esac
		done
            # Restarting uwsgi
            if [ -e /etc/init.d/uwsgi ]; then
                echo "reloading uwsgi module"
                touch /var/lib/$DPKG_MAINTSCRIPT_PACKAGE/reload
            fi
            if [ -e /etc/init.d/apache2 ]; then
                echo "reloading apache2 module"
                service apache2 reload
            fi
	else
		source bin/activate
		./bin/sentry init sentry.conf.py
		deactivate
        fi
    ;;

    *)
    # Do nothing
    ;;
esac
